### Q.1 Write a function so that the columns of the output matrix are powers of the input vector. 
### The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.

In [3]:
import numpy as np

In [8]:
def vander(inp,N,increasing=False):
    if not increasing:
        opt = np.array([x**(N-i-1) for x in inp for i in range(N)]).reshape(inp.size,N)
    elif increasing:
        opt = np.array([x**i for x in inp for i in range(N)]).reshape(inp.size,N)
    return opt
        

In [9]:
inp = np.array([1,2,3,4])
N = 3
vander(inp,N,increasing=True)

array([[ 1,  1,  1],
       [ 1,  2,  4],
       [ 1,  3,  9],
       [ 1,  4, 16]])

In [10]:
vander(inp,N,increasing=False)

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [16,  4,  1]])

### Q.2 Write a function to find moving average in an array over a window:
### Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [27]:
import numpy as np

In [64]:
def moving_avg(a,n):
    asum = np.cumsum(a,dtype=float)
    asum[n:] = asum[n:] - asum[:-n]
    return asum[n-1:]/n

In [65]:
a = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
b = np.array(a) 
moving_avg(b,3)

array([  5.        ,   4.66666667,   5.66666667,   6.66666667,
         9.66666667,  28.66666667,  49.33333333,  72.66666667,
        84.        ,  93.33333333, 116.33333333])